services:
  redis:
    image: redis:7-alpine
    container_name: shake-to-go-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shake-to-go-network
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  shake-to-go-network:
    driver: bridge